# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tidy Geospatial Datacubes (tidy xarray)
author: Emma Marshall, Scott Henderson, Deepak Cherian
#logo: logo.png

#only want to include files listed in toc (not sure this will work)
# found here: https://github.com/executablebooks/jupyter-book/pull/1123
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'
  allow_errors: true
  timeout: 500

#enable parsing of latex-stype math blocks
parse:
    myst_enable_extensions:
     - amsmath

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/dcherian/tidy-xarray  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab" 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
#  - sphinxext.opengraph
  config:
    ogp_site_url: "https://e-marshall.github.io/tidy_xr/intro.html"
    ogp_image: "https://e-marshall.github.io/tidy_xr/_static/itslive_explore_img.png"
    ogp_description_length: 200